spring.application.name=finance-tracker

spring.data.mongodb.uri=mongodb+srv://vikasvashistha68_db_user:VhdAXsYnr2BpNv4q@cluster0.zfcxgnk.mongodb.net/finance_tracker?retryWrites=true&w=majority&appName=Cluster0