spring.application.name=finance-tracker
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://<vikasvashistha68_db_user>:<yeFcvPnYKvpAfP3t>@cluster0.ogkjnig.mongodb.net/?appName=Cluster0}
server.port=${PORT:8080}
